# Generated by Django 4.1.6 on 2023-02-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_bidder_comment_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_datetime',
            new_name='bid_dateTime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_dateTime',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='end_date',
            new_name='end_dateTime',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='start_date',
            new_name='start_dateTime',
        ),
    ]
