# Generated by Django 4.1.6 on 2023-02-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bid_datetime_bid_bid_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_dateTime',
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
