# Generated by Django 4.1.6 on 2023-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
